# Generated by Django 6.0.4 on 2026-04-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en soles', max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible', verbose_name='Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='erp_product_codigo_bec135_idx'), models.Index(fields=['nombre'], name='erp_product_nombre_ffd742_idx')],
            },
        ),
    ]
